{"name": "test_incorrect_cred_login_fail", "status": "passed", "description": "Логин с неверным логином и паролем", "start": 1720286493258, "stop": 1720286493496, "uuid": "bb0c3ccc-efcc-4a2e-ab9d-fbb3777374b2", "historyId": "0fbfb522db9eb547a7efe6606f8aff34", "testCaseId": "0fbfb522db9eb547a7efe6606f8aff34", "fullName": "tests.test_login_user.TestLoginUser#test_incorrect_cred_login_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "DESKTOP-LU3QF62"}, {"name": "thread", "value": "19692-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}